### ISSUE TITLE
targets

### ISSUE THREAD

**Issue by IpekUyguner** [yhifny/keras-kaldi#2]
Hi!! I am new to speech recognition and Kaldi at all. I do not get how the labels are generated, does the Kaldi toolkit create them automatically? Where has the targets_mono.txt file been generated? I run kaldi recipe including all steps but this file is not existing anywhere in the folders.
Thanks:)

**Comment by yhifny** [comment]
They are not generated automatically. The targets are generated in my step "Generate the alignments for train/dev".
